FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install --include=dev @testing-library/react @testing-library/jest-dom jest cypress jest-junit @babel/core @babel/preset-env @babel/preset-react babel-jest identity-obj-proxy wait-on
COPY . .
CMD ["npm", "start"] 